version: '3'

services:
  webserver:
    build: ./docker/webserver
    hostname: ${HOST}
    image: the_web
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs:/var/log/apache2
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=${DB}
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"    