version: '3'

services:
  webserver:
    build: ./docker/webserver
    hostname: ${HOST}
    image: the_web
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs:/var/log/apache2
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"    