version: '2'

services:
  webserver:
    build: ./docker/webserver
    hostname: myweb.test
    image: the_web
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/log/apache2
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=dbtest